apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruitsjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruitsjs
  template:
    metadata:
      labels:
        app: fruitsjs
    spec:
      containers:
      - name: my-fruits-nodejs
        image: regevamit/fruitsjs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
