apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruitsjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruitsjs
  template:
    metadata:
      labels:
        app: fruitsjs
    spec:
      containers:
      - image: nginx:latest
        name: my-fruits-nginx