apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruitsjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruitsjs
  template:
    metadata:
      labels:
        app: fruitsjs
    spec:
      containers:
      - image: fruitsjs:latest
        name: my-fruits-nginx
        ports:
        - containerPort: 3000
      - image: mongodb
        name: mongodb:latest
        ports:
        - containerPort: 27017