apiVersion: v1
kind: Service
metadata:
  name: fruitsjs-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: "nodejs"
  - port: 27017
    protocol: TCP
    targetPort: 27017
    name: "mongodb"
  selector:
    app: fruitsjs
  type: NodePort