apiVersion: v1
kind: Service
metadata:
  name: fruitsjs-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: fruitsjs
  type: ClusterIP